// Teste das Requisições REST dos prestadores
@baseURL = http://localhost:4000/api/Politicos

// GET - Lista todos os registros
GET {{baseURL}}
Content-Type: application/json


###
// POST - Insere uma nova bebida
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "José Penis",
    "partido": "Partido A",
    "cargo": "Deputado Federal",
    "data_filiação": "2020-01-15",
    "valor_ajuda_mensal": 5000,
    "numeroUrna": 12345
}