// Teste das Requisições REST dos políticos
@baseURL = http://localhost:4000/api/politicos

// GET - Lista todos os políticos
GET {{baseURL}}
Content-Type: application/json

###
// GET - Lista um político pelo id
GET {{baseURL}}/id/654fab55695988a59fc129be
Content-Type: application/json

###
// DELETE - Apaga um político pelo id
DELETE {{baseURL}}/654fab55695988a59fc129be
Content-Type: application/json