// Teste do endpoint usuários
@baseURL = http://localhost:4000/api/usuarios
###
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "Erick Rosa Simão",
    "email": "erick.rosa@gmail.com",
    "senha": "Erick.2023"
}


###
// POST - Efetuar o login
POST {{baseURL}}/login
Content-Type: application/json

{
    "email": "erick.rosa@gmail.com",
    "senha": "Erick.2023"
}

###
// GET - Obtem os usuários
GET {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1OTRlYTE5NDc0ZGM1MmMzOTllMWRiIn0sImlhdCI6MTcwMDM1NTE2NiwiZXhwIjoxNzAxMDc1MTY2fQ.iXokHe8PlAOze7JoIbFVsojmMn99UeVNsICXxhFgiKg

###
// DELETE - Remove o usuário pelo id
DELETE {{baseURL}}/6551114e37ea6b38e124ea55
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1OTRlYTE5NDc0ZGM1MmMzOTllMWRiIn0sImlhdCI6MTcwMDM1NTE2NiwiZXhwIjoxNzAxMDc1MTY2fQ.iXokHe8PlAOze7JoIbFVsojmMn99UeVNsICXxhFgiKg

###
// PUT - Edita o usuário pelo id
PUT {{baseURL}}/6551114e37ea6b38e124ea55
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjU1OTRlYTE5NDc0ZGM1MmMzOTllMWRiIn0sImlhdCI6MTcwMDM1NTE2NiwiZXhwIjoxNzAxMDc1MTY2fQ.iXokHe8PlAOze7JoIbFVsojmMn99UeVNsICXxhFgiKg

{   
    "nome": "Laís Carvalho",
    "email": "lais.mesquita@gmail.com",
    "ativo": true,
    "tipo": "Gestor",
    "senha": "Laís.2023",
    "avatar": "https://ui-avatars.com/api/?name=Laís+Carvalho&background=F00&color=00F"
}